Document: unstrung
Title: Debian unstrung Manual
Author: <insert document author here>
Abstract: This manual describes what unstrung is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/unstrung/unstrung.sgml.gz

Format: postscript
Files: /usr/share/doc/unstrung/unstrung.ps.gz

Format: text
Files: /usr/share/doc/unstrung/unstrung.text.gz

Format: HTML
Index: /usr/share/doc/unstrung/html/index.html
Files: /usr/share/doc/unstrung/html/*.html
